
/*
 * 
 */

package v.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Nov 30 14:10:44 PYST 2011
 * Generated source version: 2.3.1-patch-01
 * 
 */


@WebServiceClient(name = "PagoWebServiceService", 
                  wsdlLocation = "http://localhost:8080/v_ejb/PagoWebService?wsdl",
                  targetNamespace = "http://ws.v/") 
public class PagoWebServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.v/", "PagoWebServiceService");
    public final static QName PagoWebServicePort = new QName("http://ws.v/", "PagoWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/v_ejb/PagoWebService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/v_ejb/PagoWebService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PagoWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PagoWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagoWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PagoWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public PagoWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PagoWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PagoWebService
     */
    @WebEndpoint(name = "PagoWebServicePort")
    public PagoWebService getPagoWebServicePort() {
        return super.getPort(PagoWebServicePort, PagoWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagoWebService
     */
    @WebEndpoint(name = "PagoWebServicePort")
    public PagoWebService getPagoWebServicePort(WebServiceFeature... features) {
        return super.getPort(PagoWebServicePort, PagoWebService.class, features);
    }

}
