package v.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Nov 29 00:36:00 PYST 2011
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://ws.v/", name = "PagoWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface PagoWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registrarPagos", targetNamespace = "http://ws.v/", className = "v.ws.RegistrarPagos")
    @WebMethod
    @ResponseWrapper(localName = "registrarPagosResponse", targetNamespace = "http://ws.v/", className = "v.ws.RegistrarPagosResponse")
    public java.util.List<v.ws.PagoWs> registrarPagos(
        @WebParam(name = "pagos", targetNamespace = "")
        java.util.List<v.ws.PagoWs> pagos
    );
}
